apiVersion: v2
name: temporal-worker-controller
description: A Helm chart for the Temporal Worker Controller (Atlan fork with scale subresource)
type: application
version: 1.2.0-atlan-1.7
appVersion: 1.2.0