{{- if .Values.prometheus.enabled }}
{{- $fullname := include "temporal-worker-controller.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    {{- include "temporal-worker-controller.labels" . | nindent 4 }}
  name: {{ $fullname }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "temporal-worker-controller.selectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    {{- include "temporal-worker-controller.labels" . | nindent 4 }}
  name: {{ $fullname }}-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      {{- include "temporal-worker-controller.selectorLabels" . | nindent 6 }}
{{- end }}
